### ISSUE TITLE
Live preview

### ISSUE THREAD

**Issue by TheChilliPL** [steven-kraft/obsidian-markdown-furigana#13]
Is there any chance this plugin could support live preview? As with other formatting, it'd show up as the original `{漢字|かんじ}` when the cursor is inside or next to it, and it'd change to <ruby>漢字<rp>【</rp><rt>かんじ</rt><rp>】</rp></ruby> otherwise.

**Comment by steven-kraft** [comment]
Sure, I'll look into it

**Comment by shookieTea** [comment]
Really looking forward to this feature if you have time for it @steven-kraft 😄 
I pretty much only use Live Preview mode in Obsidian, causing Furigana to never display.

**Comment by steven-kraft** [comment]
I took a look at this again today, but a lot of this CodeMirror stuff seems to be going right over my head 😅 If someone more knowledgeable than me can provide some insight (or even a pull request) on how I can move from the Markdown post processor to an editor extension, I would appreciate it. Otherwise, I might dig into it more when I have some more time.

Sorry!

**Comment by shookieTea** [comment]
Thanks for taking the time!
I did a little digging yesterday and found another extension's change set that appears to be for markdown -> editor https://github.com/akaalias/obsidian-footnotes/commit/ad601e5d96a9a2c6f5291df193931bfccd79c187

I wasn't sure how to implement it, but maybe this'll help!

**Comment by steven-kraft** [comment]
@shookieTea Interesting, I'll check that out! thanks!

**Comment by PlexSheep** [comment]
I just found this extension, at first i thought the extension didn't work.

**Comment by shookieTea** [comment]
Working as expected, thanks for the update! This is a game changer for Japanese study.
